/*******************************************************************************
 *  Copyright Statement:
 *  --------------------
 *  This software is protected by Copyright and the information contained
 *  herein is confidential. The software may not be copied and the information
 *  contained herein may not be used or disclosed except with the written
 *  permission of MediaTek Inc. (C) 2006
 *
 ******************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *  mtk_status.h
 *
 * Project:
 * --------
 *  BootRom Library
 *
 * Description:
 * ------------
 *  The definition of error code
 *
 * Author:
 * -------
 *  Amos Hsu (mtk00539)
 *
 *==============================================================================
 *******************************************************************************/
#ifndef _MTK_STATUS_H_
#define _MTK_STATUS_H_

//------------------------------------------------------------------------------
// return code
//------------------------------------------------------------------------------
typedef enum {

    S_DONE = 0                          // OK

    // private random error code (1~999)

    // common error code (1000~1999)
    ,S_COMMON_ERROR_BEGIN = 1000
    ,S_STOP = S_COMMON_ERROR_BEGIN      // Operation stopped by the user
    ,S_UNDEFINED_ERROR                  // Undefined error
    ,S_INVALID_ARGUMENTS                // Invalid function arguments (e.g. NULL pointer)
    ,S_INVALID_BBCHIP_TYPE              // Invalid baseband chip type
    ,S_INVALID_EXT_CLOCK                // Invalid external clock setting
    ,S_GET_DLL_VER_FAIL
    ,S_INVALID_BUF
    ,S_BUF_IS_NULL
    ,S_BUF_LEN_IS_ZERO
    ,S_BUF_SIZE_TOO_SMALL
    ,S_NOT_ENOUGH_MEMORY
    ,S_COM_PORT_OPEN_FAIL               // Failed to open COM port
    ,S_COM_PORT_SET_TIMEOUT_FAIL        // Failed to set COM port's timeout value
    ,S_COM_PORT_SET_STATE_FAIL
    ,S_COM_PORT_PURGE_FAIL
    ,S_FILEPATH_NOT_SPECIFIED_YET
    ,S_UNKNOWN_TARGET_BBCHIP            // Unknown baseband chip
    ,S_SKIP_BBCHIP_HW_VER_CHECK
    ,S_UNSUPPORTED_VER_OF_BOOT_ROM
    ,S_UNSUPPORTED_VER_OF_BOOTLOADER
    ,S_UNSUPPORTED_VER_OF_DA
    ,S_UNSUPPORTED_VER_OF_SEC_INFO
    ,S_UNSUPPORTED_VER_OF_ROM_INFO
    ,S_SEC_INFO_NOT_FOUND
    ,S_ROM_INFO_NOT_FOUND               // Cannot find ROM info
    ,S_CUST_PARA_NOT_SUPPORTED
    ,S_CUST_PARA_WRITE_LEN_INCONSISTENT
    ,S_SEC_RO_NOT_SUPPORTED
    ,S_SEC_RO_WRITE_LEN_INCONSISTENT
    ,S_ADDR_N_LEN_NOT_32BITS_ALIGNMENT
    ,S_UART_CHKSUM_ERROR
    ,S_SF_FLASH_BOOT
    ,S_EMMC_FLASH_BOOT
    ,S_NOR_FLASH_BOOT
    ,S_NAND_FLASH_BOOT
    ,S_UNSUPPORTED_VER_OF_EMI_INFO
    ,S_UNSUPPORTED_OPERATION
    ,S_COMMON_ERROR_END // END

    // BOOT ROM error code (2000~2999)
    ,S_BROM_ERROR_BEGIN = 2000
    ,S_BROM_SET_META_REG_FAIL = S_BROM_ERROR_BEGIN
    ,S_BROM_SET_FLASHTOOL_REG_FAIL
    ,S_BROM_SET_REMAP_REG_FAIL
    ,S_BROM_SET_EMI_FAIL
    ,S_BROM_DOWNLOAD_DA_FAIL            // Failed to download DA to target
    ,S_BROM_CMD_STARTCMD_FAIL           // Failed to sync with target
    ,S_BROM_CMD_STARTCMD_TIMEOUT        // Failed to sync with target
    ,S_BROM_CMD_JUMP_FAIL               // Failed to jump to DA for execution
    ,S_BROM_CMD_GET_ME_ID_FAIL
    ,S_BROM_CMD_WRITE16_MEM_FAIL
    ,S_BROM_CMD_READ16_MEM_FAIL
    ,S_BROM_CMD_WRITE16_REG_FAIL
    ,S_BROM_CMD_READ16_REG_FAIL
    ,S_BROM_CMD_CHKSUM16_MEM_FAIL
    ,S_BROM_CMD_WRITE32_MEM_FAIL
    ,S_BROM_CMD_READ32_MEM_FAIL
    ,S_BROM_CMD_WRITE32_REG_FAIL
    ,S_BROM_CMD_READ32_REG_FAIL
    ,S_BROM_CMD_CHKSUM32_MEM_FAIL
    ,S_BROM_JUMP_TO_META_MODE_FAIL      // Failed to enter META mode
    ,S_BROM_WR16_RD16_MEM_RESULT_DIFF
    ,S_BROM_CHKSUM16_MEM_RESULT_DIFF
    ,S_BROM_BBCHIP_HW_VER_INCORRECT
    ,S_BROM_FAIL_TO_GET_BBCHIP_HW_VER   // Failed to get HW ver from target
    ,S_BROM_AUTOBAUD_FAIL
    ,S_BROM_SPEEDUP_BAUDRATE_FAIL
    ,S_BROM_LOCK_POWERKEY_FAIL
    ,S_BROM_WM_APP_MSG_OUT_OF_RANGE
    ,S_BROM_NOT_SUPPORT_MT6205B
    ,S_BROM_EXCEED_MAX_DATA_BLOCKS
    ,S_BROM_EXTERNAL_SRAM_DETECTION_FAIL
    ,S_BROM_EXTERNAL_DRAM_DETECTION_FAIL
    ,S_BROM_GET_FW_VER_FAIL
    ,S_BROM_CONNECT_TO_BOOTLOADER_FAIL
    ,S_BROM_CMD_JUMP_DA_FAIL
    ,S_BROM_CMD_JUMP_BL_FAIL
    ,S_BROM_DOWNLOAD_EPP_FAIL
    ,S_BROM_EFUSE_REG_NO_MATCH_WITH_TARGET
    ,S_BROM_EFUSE_WRITE_TIMEOUT
    ,S_BROM_EFUSE_DATA_PROCESS_ERROR
    ,S_BROM_ERROR_END // END

    // DA error code (3000~3999)
    ,S_DA_ERROR_BEGIN = 3000
    ,S_DA_INT_RAM_ERROR = S_DA_ERROR_BEGIN  // Failed to detect internal RAM
    ,S_DA_EXT_RAM_ERROR                     // Failed to detect external RAM
    ,S_DA_SETUP_DRAM_FAIL
    ,S_DA_SETUP_PLL_ERR
    ,S_DA_DRAM_NOT_SUPPORT
    ,S_DA_RAM_FLOARTING
    ,S_DA_RAM_UNACCESSABLE
    ,S_DA_RAM_ERROR
    ,S_DA_DEVICE_NOT_FOUND
    ,S_DA_NOR_UNSUPPORTED_DEV_ID
    ,S_DA_NAND_UNSUPPORTED_DEV_ID
    ,S_DA_NOR_FLASH_NOT_FOUND
    ,S_DA_NAND_FLASH_NOT_FOUND
    ,S_DA_SOC_CHECK_FAIL
    ,S_DA_NOR_PROGRAM_FAILED
    ,S_DA_NOR_ERASE_FAILED
    ,S_DA_NAND_PAGE_PROGRAM_FAILED
    ,S_DA_NAND_SPARE_PROGRAM_FAILED
    ,S_DA_NAND_HW_COPYBACK_FAILED
    ,S_DA_NAND_ERASE_FAILED
    ,S_DA_TIMEOUT                           // Operation timeout (general error)
    ,S_DA_IN_PROGRESS
    ,S_DA_SUPERAND_ONLY_SUPPORT_PAGE_READ
    ,S_DA_SUPERAND_PAGE_READ_NOT_SUPPORT
    ,S_DA_SUPERAND_PAGE_PRGRAM_NOT_SUPPORT
    ,S_DA_SUPERAND_SPARE_PRGRAM_NOT_SUPPORT
    ,S_DA_SUPERAND_SPARE_READ_NOT_SUPPORT
    ,S_DA_SUPERAND_PAGE_SPARE_PRGRAM_NOT_SUPPORT
    ,S_DA_SUPERAND_COPYBACK_NOT_SUPPORT
    ,S_DA_NOR_CMD_SEQUENCE_ERR
    ,S_DA_NOR_BLOCK_IS_LOCKED
    ,S_DA_NAND_BLOCK_IS_LOCKED
    ,S_DA_NAND_BLOCK_DATA_UNSTABLE
    ,S_DA_NOR_BLOCK_DATA_UNSTABLE
    ,S_DA_NOR_VPP_RANGE_ERR
    ,S_DA_INVALID_BEGIN_ADDR
    ,S_DA_NOR_INVALID_ERASE_BEGIN_ADDR
    ,S_DA_NOR_INVALID_READ_BEGIN_ADDR
    ,S_DA_NOR_INVALID_PROGRAM_BEGIN_ADDR
    ,S_DA_INVALID_RANGE
    ,S_DA_NOR_PROGRAM_AT_ODD_ADDR
    ,S_DA_NOR_PROGRAM_WITH_ODD_LENGTH
    ,S_DA_NOR_BUFPGM_NO_SUPPORT
    ,S_DA_NAND_UNKNOWN_ERR
    ,S_DA_NAND_BAD_BLOCK
    ,S_DA_NAND_ECC_1BIT_CORRECT
    ,S_DA_NAND_ECC_2BITS_ERR
    ,S_DA_NAND_ECC_UNCORRECTABLE_ERROR
    ,S_DA_NAND_SPARE_CHKSUM_ERR
    ,S_DA_NAND_HW_COPYBACK_DATA_INCONSISTENT
    ,S_DA_NAND_INVALID_PAGE_INDEX
    ,S_DA_NFI_NOT_SUPPORT
    ,S_DA_NFI_CS1_NOT_SUPPORT
    ,S_DA_NFI_16BITS_IO_NOT_SUPPORT
    ,S_DA_NFB_BOOTLOADER_NOT_EXIST
    ,S_DA_NAND_NO_GOOD_BLOCK
    ,S_DA_BOOTLOADER_IS_TOO_LARGE
    ,S_DA_SIBLEY_REWRITE_OBJ_MODE_REGION
    ,S_DA_SIBLEY_WRITE_B_HALF_IN_CTRL_MODE_REGION
    ,S_DA_SIBLEY_ILLEGAL_CMD
    ,S_DA_SIBLEY_PROGRAM_AT_THE_SAME_REGIONS
    ,S_DA_UART_GET_DATA_TIMEOUT
    ,S_DA_UART_GET_CHKSUM_LSB_TIMEOUT
    ,S_DA_UART_GET_CHKSUM_MSB_TIMEOUT
    ,S_DA_UART_DATA_CKSUM_ERROR
    ,S_DA_UART_RX_BUF_FULL
    ,S_DA_FLASH_RECOVERY_BUF_NOT_ENOUGH
    ,S_DA_HANDSET_SEC_INFO_NOT_FOUND
    ,S_DA_HANDSET_SEC_INFO_MAC_VERIFY_FAIL
    ,S_DA_HANDSET_ROM_INFO_NOT_FOUND
    ,S_DA_HANDSET_FAT_INFO_NOT_FOUND
    ,S_DA_OPERATION_UNSUPPORT_FOR_NFB
    ,S_DA_BYPASS_POST_PROCESS
    ,S_DA_NOR_OTP_NOT_SUPPORT
    ,S_DA_NOR_OTP_EXIST
    ,S_DA_NOR_OTP_LOCKED
    ,S_DA_NOR_OTP_GETSIZE_FAIL
    ,S_DA_NOR_OTP_READ_FAIL
    ,S_DA_NOR_OTP_PROGRAM_FAIL
    ,S_DA_NOR_OTP_LOCK_FAIL
    ,S_DA_NOR_OTP_LOCK_CHECK_STATUS_FAIL
    ,S_DA_BLANK_FLASH
    ,S_DA_CODE_AREA_IS_BLANK
    ,S_DA_SEC_RO_AREA_IS_BLANK
    ,S_DA_NOR_OTP_UNLOCKED
    ,S_DA_UNSUPPORTED_BBCHIP
    ,S_DA_FAT_NOT_EXIST
    ,S_DA_EXT_SRAM_NOT_FOUND
    ,S_DA_EXT_DRAM_NOT_FOUND
    ,S_DA_MT_PIN_LOW
    ,S_DA_MT_PIN_HIGH
    ,S_DA_MT_PIN_SHORT
    ,S_DA_MT_BUS_ERROR
    ,S_DA_MT_ADDR_NOT_2BYTE_ALIGNMENT
    ,S_DA_MT_ADDR_NOT_4BYTE_ALIGNMENT
    ,S_DA_MT_SIZE_NOT_2BYTE_ALIGNMENT
    ,S_DA_MT_SIZE_NOT_4BYTE_ALIGNMENT
    ,S_DA_MT_DEDICATED_PATTERN_ERROR
    ,S_DA_MT_INC_PATTERN_ERROR
    ,S_DA_MT_DEC_PATTERN_ERROR
    ,S_DA_NFB_BLOCK_0_IS_BAD
    ,S_DA_CUST_PARA_AREA_IS_BLANK
    ,S_DA_ENTER_RELAY_MODE_FAIL
    ,S_DA_ENTER_RELAY_MODE_IS_FORBIDDEN_AFTER_META
    ,S_DA_NAND_PAGE_READ_FAILED
    ,S_DA_NAND_IMAGE_BLOCK_NO_EXIST
    ,S_DA_NAND_IMAGE_LIST_NOT_EXIST
    ,S_DA_MBA_RESOURCE_NO_EXIST_IN_TARGET
    ,S_DA_MBA_PROJECT_VERSION_NO_MATCH_WITH_TARGET
    ,S_DA_MBA_UPDATING_RESOURCE_NO_EXIST_IN_TARGET
    ,S_DA_MBA_UPDATING_RESOURCE_SIZE_EXCEED_IN_TARGET
    ,S_DA_NAND_BIN_SIZE_EXCEED_MAX_SIZE
    ,S_DA_NAND_EXCEED_CONTAINER_LIMIT
    ,S_DA_NAND_REACH_END_OF_FLASH
    ,S_DA_NAND_OTP_NOT_SUPPORT
    ,S_DA_NAND_OTP_EXIST
    ,S_DA_NAND_OTP_LOCKED
    ,S_DA_NAND_OTP_LOCK_FAIL
    ,S_DA_NAND_OTP_UNLOCKED
    ,S_DA_OTP_NOT_SUPPORT
    ,S_DA_OTP_EXIST
    ,S_DA_OTP_LOCKED
    ,S_DA_OTP_GETSIZE_FAIL
    ,S_DA_OTP_READ_FAIL
    ,S_DA_OTP_PROGRAM_FAIL
    ,S_DA_OTP_LOCK_FAIL
    ,S_DA_OTP_LOCK_CHECK_STATUS_FAIL
    ,S_DA_OTP_UNLOCKED
    ,S_DA_SEC_RO_ILLEGAL_MAGIC_TAIL
    ,S_DA_HANDSET_FOTA_INFO_NOT_FOUND
    ,S_DA_HANDSET_UA_INFO_NOT_FOUND
    ,S_DA_SB_FSM_INVALID_INFO
    ,S_DA_NFB_TARGET_DUAL_BL_PAIRED_VERSION_NOT_MATCHED_WITH_MAUI
    ,S_DA_NFB_TARGET_DUAL_BL_FEATURE_COMBINATION_NOT_MATCHED_WITH_MAUI
    ,S_DA_NFB_TARGET_IS_SINGLE_BL_BUT_PC_NOT
    ,S_DA_NFB_TARGET_IS_DUAL_BL_BUT_PC_NOT
    ,S_DA_NOR_TARGET_BL_PAIRED_VERSION_NOT_MATCHED_WITH_MAUI
    ,S_DA_NOR_TARGET_BL_FEATURE_COMBINATION_NOT_MATCHED_WITH_MAUI
    ,S_DA_NOR_TARGET_IS_NOT_NEW_BL_BUT_PC_IS
    ,S_DA_NOR_TARGET_IS_NEW_BL_BUT_PC_NOT
    ,S_DA_GEN_DA_VERSION_INFO_TEMP_ILB_FAIL
    ,S_DA_FLASH_NOT_FOUND
    ,S_DA_BOOT_CERT_NOT_EXIST
// MT6276 SV5 Bootloader
    ,S_DA_DOWNLOAD_BOOTLOADER_FLASH_DEV_IS_NONE
    ,S_DA_DOWNLOAD_BOOTLOADER_FLASH_DEV_IS_NOT_SUPPORTED
    ,S_DA_DOWNLOAD_BOOTLOADER_BEGIN_ADDR_OVERLAPS_WITH_PREVIOUS_BOUNDARY
    ,S_DA_UPDATE_BOOTLOADER_EXIST_MAGIC_NOT_MATCHED
    ,S_DA_UPDATE_BOOTLOADER_FILE_TYPE_NOT_MATCHED
    ,S_DA_UPDATE_BOOTLOADER_FILE_SIZE_EXCEEDS_BOUNDARY_ADDR
    ,S_DA_UPDATE_BOOTLOADER_BEGIN_ADDR_NOT_MATCHED
    // SV5 CBR
    ,S_DA_CBR_SET_BUF_AND_API_FAIL
    ,S_DA_CBR_NOT_FOUND
    ,S_DA_CBR_FLASH_LAYOUT_NOT_FOUND
    ,S_DA_CBR_FLASH_SPACE_INFO_NOT_FOUND
    ,S_DA_CBR_FLASH_CONFIG_NOT_FOUND
    ,S_DA_CBR_SET_ENVRIONMENT_FAILED
    ,S_DA_CBR_CREAT_FAILED
    ,S_DA_CBR_COMPARE_FAILED
    ,S_DA_CBR_WRONG_VERSION
    ,S_DA_CBR_ALREADY_EXIST
    ,S_DA_CBR_RECORD_BUF_TOO_SMALL
    ,S_DA_CBR_RECORD_NOT_EXIST
    ,S_DA_CBR_RECORD_ALREADY_EXIST
    ,S_DA_CBR_FULL
    ,S_DA_CBR_RECORD_WRITE_LEN_INCONSISTENT
    ,S_DA_CBR_UNKNOWN_ERROR
    // SV5 SEC_RO
    ,S_DA_SEC_RO_ACC_PARSE_ERROR
    // SV5 Security preprocess
    ,S_DA_HEADER_BLOCK_NOT_EXIST
    ,S_DA_S_PRE_PARSE_CUSTOMER_NAME_FAIL
    ,S_DA_S_RETRIEVE_SEC_RO_FAIL_IN_SECURE_INIT
    ,S_DA_S_FLASH_INFO_NOT_EXIST
    ,S_DA_S_MAUI_INFO_NOT_EXIST
    ,S_DA_S_BOOTLOADER_SHARE_DATA_NOT_EXIST
    // GFH
    ,S_DA_GFH_FILE_INFO_RETREIVAL_FAIL
    ,S_DA_NAND_REMARK_FAIL
    ,S_DA_ERROR_END // END

    // FlashTool error code (4000~4999)
    ,S_FT_ERROR_BEGIN = 4000
    ,S_FT_CALLBACK_DA_REPORT_FAIL = S_FT_ERROR_BEGIN
    ,S_FT_DA_NO_RESPONSE                    // No response from DA (general error)
    ,S_FT_DA_SYNC_INCORRECT
    ,S_FT_DA_VERSION_INCORRECT
    ,S_FT_DA_INIT_SYNC_ERROR                // Cannot sync with DA in the initial stage
    ,S_FT_GET_DSP_VER_FAIL
    ,S_FT_CHANGE_BAUDRATE_FAIL              // Failed to change baudrate
    ,S_FT_SET_DOWNLOAD_BLOCK_FAIL
    ,S_FT_DOWNLOAD_FAIL                     // Failed to complete download operation (general error)
    ,S_FT_DOWNLOAD_CHKSUM_MISMATCH          // Checksum of the downloaded image is incorrect
    ,S_FT_READBACK_FAIL                     // Failed to complete readback operation (general error)
    ,S_FT_FORMAT_FAIL                       // Failed to complete format operation (general error)
    ,S_FT_FINISH_CMD_FAIL                   // Failed to disconnect with DA
    ,S_FT_ENABLE_WATCHDOG_FAIL              // Failed to enable watchdog timer
    ,S_FT_NFB_DOWNLOAD_BOOTLOADER_FAIL
    ,S_FT_NFB_DOWNLOAD_CODE_FAIL
    ,S_FT_NFB_INVALID_BOOTLOADER_DRAM_SETTING
    ,S_FT_NAND_READADDR_NOT_PAGE_ALIGNMENT
    ,S_FT_NAND_READLEN_NOT_PAGE_ALIGNMENT
    ,S_FT_READ_REG16_FAIL
    ,S_FT_WRITE_REG16_FAIL
    ,S_FT_CUST_PARA_GET_INFO_FAIL
    ,S_FT_CUST_PARA_READ_FAIL
    ,S_FT_CUST_PARA_WRITE_FAIL
    ,S_FT_INVALID_FTCFG_OPERATION
    ,S_FT_INVALID_CUST_PARA_OPERATION
    ,S_FT_INVALID_SEC_RO_OPERATION
    ,S_FT_INVALID_OTP_OPERATION
    ,S_FT_POST_PROCESS_FAIL
    ,S_FT_FTCFG_UPDATE_FAIL
    ,S_FT_SEC_RO_GET_INFO_FAIL
    ,S_FT_SEC_RO_READ_FAIL
    ,S_FT_SEC_RO_WRITE_FAIL
    ,S_FT_ENABLE_SRAM_FAIL                  // Failed to enable SRAM
    ,S_FT_ENABLE_DRAM_FAIL                  // Failed to enable DRAM
    ,S_FT_FS_FINDFIRSTEX_FAIL
    ,S_FT_FS_FINDNEXTEX_FAIL
    ,S_FT_FS_FOPEN_FAIL
    ,S_FT_FS_GETFILESIZE_FAIL
    ,S_FT_FS_READ_FAIL
    ,S_FT_FS_FILENAME_INVALID
    ,S_FT_FS_FILENAME_TOO_LONG
    ,S_FT_FS_ASSERT
    ,S_FT_OTP_ADDR_NOT_WORD_ALIGNMENT
    ,S_FT_OTP_LENGTH_NOT_WORD_ALIGNMENT
    ,S_FT_OTP_INVALID_ADDRESS_RANGE
    ,S_FT_NAND_READ_TO_BUFFER_NOT_SUPPORT
    ,S_FT_GET_PROJECT_ID_FAIL
    ,S_FT_ENFB_ROM_FILE_SMALL_THAN_HEADER_DESCRIBE
    ,S_FT_RW_EXTRACT_NFB_FAIL
    ,S_FT_MEMORY_TEST_FAIL
    ,S_FT_CHECK_BOOTLOADER_FEATURE_FAIL
    ,S_FT_ENABLE_BOOT_FAIL
    ,S_FT_FORBIDDEN_DOWNLOAD_BOOTLOADER_FAIL_SUART
    ,S_FT_SPK_FEATURE_FAIL
    ,S_FT_FILE_NOT_EXIST
    ,S_FT_CAN_NOT_OPEN_FILE
    ,S_FT_INVALID_FORMAT
    ,S_FT_COMMUNICATION_ERROR
    ,S_FT_PROTOCOL_EXCEPTION
    ,S_FT_COMBO_MEMORY_SETTING_NOT_MATCHED

    ,S_FT_ERROR_END // END

    // FlashTool Handle error code (5000~5999)
    ,S_FTHND_ERROR_BEGIN = 5000
    ,S_AUTH_HANDLE_IS_NOT_READY = S_FTHND_ERROR_BEGIN
    ,S_INVALID_AUTH_FILE
    ,S_INVALID_DA_FILE
    ,S_DA_HANDLE_IS_NOT_READY
    ,S_FTHND_ILLEGAL_INDEX
    ,S_FTHND_HANDLE_BUSY_NOW
    ,S_FTHND_FILE_IS_UPDATED
    ,S_FTHND_FILE_IS_NOT_LOADED_YET
    ,S_FTHND_FILE_LOAD_FAIL
    ,S_FTHND_FILE_UNLOAD_FAIL
    ,S_FTHND_LIST_IS_EMPTY
    ,S_DL_SCAT_INCORRECT_FORMAT
    ,S_DL_SCAT_ADDR_IS_NOT_WORD_ALIGN
    ,S_DL_SCAT_OFFSET_IS_NOT_WORD_ALIGN
    ,S_DL_SCAT_ADDR_IS_NOT_ASCENDING_ORDER
    ,S_DL_SCAT_JUMPTABLE_IS_NOT_ABSOLUTE_ADDR
    ,S_DL_LOAD_REGION_IS_OVERLAP
    ,S_DL_LOAD_REGION_NOT_FOUND
    ,S_DL_NOT_RESOURCE_BIN
    ,S_DL_MULTIBIN_MECHANISM_DISABLED
    ,S_DL_RESOURCE_NOT_MATCH_IN_JUMPTABLE
    ,S_DL_RESOURCE_MUST_DOWNLOAD_WITH_JUMPTABLE
    ,S_DL_OVERLAP_WITH_EXISTING_RESOURCE
    ,S_DL_INVALID_RESOURCE_BIN
    ,S_DL_JUMPTABLE_INCONSISTENT_WITH_SCAT
    ,S_DL_INVALID_JUMPTABLE
    ,S_DL_REGION_ADDR_INCONSISTENT_WITH_SCAT
    ,S_DL_REGION_ADDR_INCONSISTENT_WITH_RESOURCE_ADDR
    ,S_DL_INVALID_BOOTLOADER
    ,S_DL_INVALID_BOOTLOADER_CHKSUM_SEED
    ,S_DL_BOOTLOADER_IS_NOT_LOADED_YET
    ,S_DL_BOOTLOADER_NOT_FOUND
    ,S_DL_REMOTE_FILE_UNSUPPORTED_BY_BL_AUTOLOAD
    ,S_DLIST_SAME_FLASHID_AND_BBCHIP_SW_VER
    ,S_DLIST_SAME_BBCHIP_SW_VER
    ,S_DLIST_BBCHIP_HW_VER_NOT_MATCHED
    ,S_DLIST_NO_MATCHED_DL_HANDLE_FOUND
    ,S_DLIST_DL_HANDLE_NOT_IN_LIST
    ,S_DLIST_DL_HANDLE_ALREADY_IN_LIST
    ,S_FTHND_CALLBACK_REMOTE_GET_FILE_LEN_FAIL
    ,S_FTHND_CALLBACK_REMOTE_READ_FILE_FAIL
    ,S_FTHND_CALLBACK_FILE_INTEGRITY_CHECK_FAIL
    ,S_UNSUPPORTED_VER_OF_AUTH_FILE
    ,S_DL_PROJECT_ID_DIFF_BETWEEN_MAIN_CODE_AND_JUMP_TBL
    ,S_DL_SCAT_OPEN_FAIL
    ,S_FTHND_CALLBACK_COM_INIT_STAGE_FAIL
    ,S_DL_UNSECURE_MAUI_TO_SECURE_BB
    ,S_FTHND_CALLBACK_REMOTE_GET_SIG_LEN_FAIL
    ,S_FTHND_CALLBACK_REMOTE_READ_SIG_FAIL
    ,S_DL_RESOURCE_MUST_DOWNLOAD_WITH_ANOTHERBIN
    ,S_DL_RESOURCE_MUST_DOWNLOAD_WITH_ENFB
    ,S_DL_PROJECT_ID_DIFF_BETWEEN_MAIN_CODE_AND_RESOURCE_BIN
    ,S_DL_PROJECT_ID_DIFF_AMONG_RESOURCE_BIN
    ,S_DL_UNSECURE_BOOTLOADER_TO_SECURE_BB
    ,S_DL_GET_DRAM_SETTING_FAIL
    ,S_DL_FOTA_INFO_IMAGE_NUMBER_NOT_MATCH_WITH_SCATTER_FILE
    ,S_DL_PROJECT_ID_DIFF_BETWEEN_THIRD_ROM_AND_RESOURCE_BIN
    ,S_DL_FOTA_SEC_INFO_MAC_ADDR_NOT_MATCH_WITH_MAUI
    ,S_DL_PC_NFB_DUAL_BL_PAIRED_VERSION_NOT_MATCHED_WITH_MAUI
    ,S_DL_PC_NFB_DUAL_BL_FEATURE_COMBINATION_NOT_MATCHED_WITH_MAUI
    ,S_DL_PC_NOR_XIP_BL_PAIRED_VERSION_NOT_MATCHED_WITH_MAUI
    ,S_DL_PC_NOR_XIP_BL_FEATURE_COMBINATION_NOT_MATCHED_WITH_MAUI
    ,S_DL_INVALID_BOOT_CERT
	,S_DL_FILE_NOT_FOUND
    ,S_INVALID_SCERT_FILE
    ,S_UNSUPPORTED_VER_OF_SCERT_FILE
    ,S_UNSUPPORTED_TARGET_CHIP_VERSION
    ,S_SCERT_HANDLE_IS_NOT_READY
    ,S_FTHND_ROM_ENTRIES_NOT_CREATED_YET
    ,S_FTHND_NO_ROM_IS_ENABLED

    ,S_FTHND_ERROR_END // END

    // security error code (6000~6999)
    ,S_SECURITY_ERROR_BEGIN = 6000
    ,S_SECURITY_CALLBACK_SLA_CHALLENGE_FAIL = S_SECURITY_ERROR_BEGIN
    ,S_SECURITY_SLA_WRONG_AUTH_FILE
    ,S_SECURITY_SLA_INVALID_AUTH_FILE
    ,S_SECURITY_SLA_CHALLENGE_FAIL
    ,S_SECURITY_SLA_FAIL
    ,S_SECURITY_DAA_FAIL
    ,S_SECURITY_SBC_FAIL
    ,S_SECURITY_ME_ID_FAIL
    ,S_SECURITY_SF_SECURE_VER_CHECK_FAIL
    ,S_SECURITY_SF_HANDSET_SECURE_CUSTOM_NAME_NOT_MATCH
    ,S_SECURITY_SF_FTCFG_LOCKDOWN
    ,S_SECURITY_SF_CODE_DOWNLOAD_FORBIDDEN
    ,S_SECURITY_SF_CODE_READBACK_FORBIDDEN
    ,S_SECURITY_SF_CODE_FORMAT_FORBIDDEN
    ,S_SECURITY_SF_SEC_RO_DOWNLOAD_FORBIDDEN
    ,S_SECURITY_SF_SEC_RO_READBACK_FORBIDDEN
    ,S_SECURITY_SF_SEC_RO_FORMAT_FORBIDDEN
    ,S_SECURITY_SF_FAT_DOWNLOAD_FORBIDDEN
    ,S_SECURITY_SF_FAT_READBACK_FORBIDDEN
    ,S_SECURITY_SF_FAT_FORMAT_FORBIDDEN
    ,S_SECURITY_SF_RESTRICTED_AREA_ACCESS_FORBIDDEN
    ,S_SECURITY_SECURE_CUSTOM_NAME_NOT_MATCH_BETWEEN_AUTH_AND_DL_HANDLE
    ,S_SECURITY_SECURE_CUSTOM_NAME_NOT_MATCH_BETWEEN_AUTH_AND_BL
    ,S_SECURITY_DOWNLOAD_FILE_IS_CORRUPTED
    ,S_SECURITY_NOT_SUPPORT
    ,S_SECURITY_BOOTLOADER_IMAGE_SIGNATURE_FAIL
    ,S_SECURITY_BOOTLOADER_ELDER_SW_VERSION_CANNOT_BE_DOWNLOADED
    ,S_SECURITY_SW_VERSION_IN_HEADER_IS_NOT_MATCH_THAT_IN_ROM_INFO
    ,S_SECURITY_BOOTLOADER_IMAGE_NO_SIGNATURE
    ,S_SECURITY_BOOTLOADER_CORRUPTED_SCATTER_FILE
    ,S_SECURITY_SECURE_USB_DL_NO_MAUI_IN_SCATTER_FILE
    ,S_SECURITY_SEND_CERT_FAIL
    ,S_SECURITY_SEND_AUTH_FAIL
    ,S_SECURITY_GET_SEC_CONFIG_FAIL
    ,S_SECURITY_GET_ME_ID_FAIL

    ,S_SECURITY_ERROR_END // END

    // expand to 32bits width
    ,S_MAX_STATUS_WIDTH = 0x7FFFFFFF

} STATUS_E;

#define STATUS_CODE(err_code, private_err_code)\
    ((S_COMMON_ERROR_BEGIN<=err_code)?err_code:private_err_code)

#endif
